### ISSUE TITLE
AttributeError: 'Token' object has no attribute 'text'

### ISSUE THREAD

**Issue by ekaterinatretyak** [avidale/dependency-paraphraser#2]
Hi there!
Trying to use dependency-paraphraser for English. As the word2vec model I use 'word2vec-google-news-300' and load it like this:

`import dependency_paraphraser.udpipe`
`import gensim.downloader`

`w2v_model = gensim.downloader.load('word2vec-google-news-300')`

`path = 'english-ewt-ud-2.5-191206.udpipe`
`pipe = dependency_paraphraser.udpipe.Model(path)`
`projector = dependency_paraphraser.udpipe.en_udpipe_projector`

`text = 'in April 2012 they released the videoclip for a new single entitled Giorgio Mastrota.'`
`for i in range(3):`
`    print(dependency_paraphraser.udpipe.paraphrase(text, pipe, w2v=w2v_model, projector=projector, tree_temperature=1))`

I get the following error:

Traceback (most recent call last):
  File "dependency_rewriter.py", line 34, in <module>
    print(dependency_paraphraser.udpipe.paraphrase(text, pipe, w2v=w2v_model, projector=projector, tree_temperature=1))
  File "/home/.local/lib/python3.7/site-packages/dependency_paraphraser/udpipe.py", line 90, in paraphrase
    toks, w2v=w2v, morph_vocab=morph, min_sim=min_sim, p_rep=p_rep,
  File "/home/.local/lib/python3.7/site-packages/dependency_paraphraser/synonyms.py", line 48, in replace_synonyms
    result.append(token.text)
AttributeError: 'Token' object has no attribute 'text'

How could I fix it? Thanks in advance for answer!

**Comment by avidale** [comment]
This issue should have been fixed in the release 0.0.5 https://pypi.org/project/dependency-paraphraser/0.0.5/
